#!/bin/bash

docker run --rm -d \
        --user="$(id -u)" \
        --workdir="/home/$(id -un)" \
        -v /home/$(id -un):/home/$(id -un):rw\
        -v /etc/group:/etc/group:ro \
        -v /etc/passwd:/etc/passwd:ro \
        -v /etc/shadow:/etc/shadow:ro \
        -v /etc/sudoers.d/:/etc/sudoers.d:ro \
 	-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
 	-e DISPLAY=unix$DISPLAY \
 	grosalesr/netbeans:ubuntu
